version: "3.8"

services: 
  
  es_node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es_node1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/es_node1:/usr/share/elasticsearch/data
    environment:
      - node.name=es_node1
      - discovery.seed_hosts=es_node2,es_node3,es_node4
      - cluster.initial_master_nodes=es_node1,es_node2,es_node3,es_node4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es_node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es_node2
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/es_node2:/usr/share/elasticsearch/data
    environment:
      - node.name=es_node2
      - discovery.seed_hosts=es_node1,es_node3,es_node4
      - cluster.initial_master_nodes=es_node1,es_node2,es_node3,es_node4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es_node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es_node3
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/es_node3:/usr/share/elasticsearch/data
    environment:
      - node.name=es_node3
      - discovery.seed_hosts=es_node1,es_node2,es_node4
      - cluster.initial_master_nodes=es_node1,es_node2,es_node3,es_node4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es_node4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es_node4
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data/elasticsearch/es_node4:/usr/share/elasticsearch/data
    environment:
      - node.name=es_node4
      - discovery.seed_hosts=es_node1,es_node2,es_node3
      - cluster.initial_master_nodes=es_node1,es_node2,es_node3,es_node4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports: 
      - 5601:5601
    depends_on: 
      - es_node1
      - es_node2
      - es_node3
      - es_node4

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.14.1"
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: 
      context: ./server
    container_name: backend
    volumes:
      - ./server:/app
      - ./logs:/var/log/nginx
    ports:
      - 5000:5000

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - 80:80

volumes: 
  logs:

    
